// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kennel.proto

package kennel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Borker struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Breed                string   `protobuf:"bytes,3,opt,name=breed,proto3" json:"breed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Borker) Reset()         { *m = Borker{} }
func (m *Borker) String() string { return proto.CompactTextString(m) }
func (*Borker) ProtoMessage()    {}
func (*Borker) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb7f415756a5cfef, []int{0}
}

func (m *Borker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Borker.Unmarshal(m, b)
}
func (m *Borker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Borker.Marshal(b, m, deterministic)
}
func (m *Borker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Borker.Merge(m, src)
}
func (m *Borker) XXX_Size() int {
	return xxx_messageInfo_Borker.Size(m)
}
func (m *Borker) XXX_DiscardUnknown() {
	xxx_messageInfo_Borker.DiscardUnknown(m)
}

var xxx_messageInfo_Borker proto.InternalMessageInfo

func (m *Borker) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Borker) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Borker) GetBreed() string {
	if m != nil {
		return m.Breed
	}
	return ""
}

func init() {
	proto.RegisterType((*Borker)(nil), "kennel.Borker")
}

func init() { proto.RegisterFile("kennel.proto", fileDescriptor_bb7f415756a5cfef) }

var fileDescriptor_bb7f415756a5cfef = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4e, 0xcd, 0xcb,
	0x4b, 0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x9c, 0xb8, 0xd8,
	0x9c, 0xf2, 0x8b, 0xb2, 0x53, 0x8b, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e, 0xd6, 0xa4, 0xa2, 0xd4, 0xd4, 0x14,
	0x09, 0x66, 0xb0, 0x20, 0x84, 0x93, 0xc4, 0x06, 0x36, 0xd2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xa9, 0xc0, 0xcf, 0x84, 0x62, 0x00, 0x00, 0x00,
}
