// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifier.proto

package notifier

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Notification struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Read                 bool                 `protobuf:"varint,5,opt,name=read,proto3" json:"read,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c0fc606bc4470de, []int{0}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Notification) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Notification) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

type SendNotificationRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendNotificationRequest) Reset()         { *m = SendNotificationRequest{} }
func (m *SendNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*SendNotificationRequest) ProtoMessage()    {}
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c0fc606bc4470de, []int{1}
}

func (m *SendNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendNotificationRequest.Unmarshal(m, b)
}
func (m *SendNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendNotificationRequest.Marshal(b, m, deterministic)
}
func (m *SendNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendNotificationRequest.Merge(m, src)
}
func (m *SendNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_SendNotificationRequest.Size(m)
}
func (m *SendNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendNotificationRequest proto.InternalMessageInfo

func (m *SendNotificationRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SendNotificationRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SendNotificationRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Notification)(nil), "notifier.Notification")
	proto.RegisterType((*SendNotificationRequest)(nil), "notifier.SendNotificationRequest")
}

func init() { proto.RegisterFile("notifier.proto", fileDescriptor_1c0fc606bc4470de) }

var fileDescriptor_1c0fc606bc4470de = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xce, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0x71, 0x39, 0x34, 0xfd, 0x73, 0xa0, 0x0e, 0x27, 0xa4, 0x5a, 0x5d, 0x88, 0x3a, 0x79,
	0x72, 0x25, 0x98, 0x18, 0x19, 0x59, 0x18, 0x0c, 0x7b, 0xe5, 0xc4, 0xd7, 0xca, 0x52, 0x6b, 0x07,
	0xe7, 0xf2, 0x38, 0xbc, 0x2b, 0xc2, 0xc1, 0x88, 0xb5, 0xdb, 0x7d, 0x4f, 0xbf, 0xe1, 0x03, 0xeb,
	0x10, 0xd9, 0x1f, 0x3d, 0x25, 0xdd, 0xa7, 0xc8, 0x11, 0x97, 0xa5, 0xb7, 0x0f, 0xa7, 0x18, 0x4f,
	0x67, 0xda, 0xe7, 0x7f, 0x3b, 0x1e, 0xf7, 0xec, 0x2f, 0x34, 0xb0, 0xbd, 0xf4, 0xd3, 0x74, 0xf7,
	0x25, 0xe0, 0xee, 0x2d, 0xaf, 0x3b, 0xcb, 0x3e, 0x06, 0x5c, 0x43, 0xe5, 0x9d, 0x14, 0x8d, 0x50,
	0xb5, 0xa9, 0xbc, 0xc3, 0x7b, 0xa8, 0xd9, 0xf3, 0x99, 0x64, 0xd5, 0x08, 0xb5, 0x32, 0x53, 0xa0,
	0x84, 0x45, 0x17, 0x03, 0x53, 0x60, 0x79, 0x93, 0xff, 0x25, 0xf1, 0x19, 0xa0, 0x4b, 0x64, 0x99,
	0xdc, 0xc1, 0xb2, 0x9c, 0x35, 0x42, 0xdd, 0x3e, 0x6e, 0xf5, 0xc4, 0xd0, 0x85, 0xa1, 0x3f, 0x0a,
	0xc3, 0xac, 0x7e, 0xd7, 0x2f, 0x8c, 0x08, 0xb3, 0x44, 0xd6, 0xc9, 0xba, 0x11, 0x6a, 0x69, 0xf2,
	0xbd, 0x6b, 0x61, 0xf3, 0x4e, 0xc1, 0xfd, 0x27, 0x1a, 0xfa, 0x1c, 0x69, 0x60, 0xdc, 0xc0, 0x62,
	0x1c, 0x28, 0x1d, 0xfe, 0xb8, 0xf3, 0x9f, 0x7c, 0xbd, 0x9a, 0xdc, 0xce, 0x33, 0xeb, 0xe9, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x7f, 0xf8, 0x11, 0xf2, 0x47, 0x01, 0x00, 0x00,
}
